name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ID_RSA }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 180.71.58.10 >> ~/.ssh/known_hosts

      - name: Copy project files via scp
        run: |
          echo "Copying project files to remote server..." | tee copy_files.log
          scp -P 2002 -o StrictHostKeyChecking=no -r build/libs/*.jar ubuntu@180.71.58.10:/home/ubuntu/spring-boot-app/ 2>&1 | tee -a copy_files.log

      - name: Execute remote commands
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@180.71.58.10 -p 2002 "
            echo 'Killing existing Java process...' | tee -a /home/ubuntu/spring-boot-app/deploy.log &&
            pkill -f 'java -jar' || true | tee -a /home/ubuntu/spring-boot-app/deploy.log &&
            nohup /application/jdk-17.0.11/bin/java -Dserver.port=14343 -Dobj_name=SPRING_BOOT_APP -jar /home/ubuntu/spring-boot-app/*.jar > /home/ubuntu/spring-boot-app/app.log 2>&1 &
          "
